<?php

namespace AppBundle\Repository;

/**
 * StatisticTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
